DROP TABLE IF EXISTS EXAMPLE;
CREATE TABLE EXAMPLE(ID INT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO EXAMPLE VALUES(1, 'Hello');
INSERT INTO EXAMPLE VALUES(2, 'World');
SELECT * FROM EXAMPLE ORDER BY ID;
UPDATE EXAMPLE SET NAME='Hi' WHERE ID=1;
--DELETE FROM EXAMPLE WHERE ID=2;